spring.application.name=reactive-backend

spring.datasource.url=jdbc:mysql://localhost:3306/reactive?createDatabaseIfNotExist=true&serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=Root1234!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
jwt.secret=MiClaveSuperUltraSecretaReactive2026QueTieneMasDe32Caracteres
jwt.expiration=86400000